# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84c6dcac1d7ed7af341cb79500392896d505c134b25ea5d5c4afd7ef3289d295ca266a6b4c77e4b1ced800968ba96d64738c4f4eaaa5ee26848f48df72d66d90

test:
  secret_key_base: 4eb45e18b19b3898132783cbf89267788a99d5849f6f1cf5e53c7c8268839ed0df8decba9fc40dce2e659ab8dc9d966f679240de5fdbb57633c49f14ddeae062

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
